package org.flowr.framework.core.constants;

/**
 * 
 * 
 * @author Chandra Shekhar Pandey
 * Copyright © 2018 by Chandra Shekhar Pandey. All rights reserved.
 */

public class FrameworkConstants {

	public static final String FRAMEWORK_SERVICE					= "FRAMEWORK_SERVICE";
	public static final String FRAMEWORK_SERVICE_PROVIDER			= "FRAMEWORK_SERVICE_PROVIDER";
	public static final String FRAMEWORK_SERVICE_EVENT				= "FRAMEWORK_SERVICE_EVENT";
	public static final String FRAMEWORK_SERVICE_NOTIFICATION		= "FRAMEWORK_SERVICE_NOTIFICATION";
	public static final String FRAMEWORK_SERVICE_PROMISE			= "FRAMEWORK_SERVICE_PROMISE";
	public static final String FRAMEWORK_SERVICE_PROMISE_PHASED		= "FRAMEWORK_SERVICE_PROMISE_PHASED";
	public static final String FRAMEWORK_SERVICE_PROMISE_SCHEDULED	= "FRAMEWORK_SERVICE_PROMISE_SCHEDULED";
	public static final String FRAMEWORK_SERVICE_PROMISE_STAGED		= "FRAMEWORK_SERVICE_PROMISE_STAGED";
	public static final String FRAMEWORK_SERVICE_REGISTRY			= "FRAMEWORK_SERVICE_REGISTRY";
	public static final String FRAMEWORK_SERVICE_ROUTING			= "FRAMEWORK_SERVICE_ROUTING";
	public static final String FRAMEWORK_SERVICE_SUBSCRIPTION		= "FRAMEWORK_SERVICE_SUBSCRIPTION";
	public static final String FRAMEWORK_SERVICE_MANAGEMENT			= "FRAMEWORK_SERVICE_MANAGEMENT";
	
	public static final String FRAMEWORK_PIPELINE_PROMISE			= "FRAMEWORK_PIPELINE_PROMISE";
	public static final String FRAMEWORK_PIPELINE_PROMISE_PHASED	= "FRAMEWORK_PIPELINE_PROMISE_PHASED";
	public static final String FRAMEWORK_PIPELINE_PROMISE_SCHEDULED	= "FRAMEWORK_PIPELINE_PROMISE_SCHEDULED";
	public static final String FRAMEWORK_PIPELINE_PROMISE_STAGED	= "FRAMEWORK_PIPELINE_PROMISE_STAGED";
	public static final String FRAMEWORK_PIPELINE_PROMISE_STREAM	= "FRAMEWORK_PIPELINE_PROMISE_STREAM";
	public static final String FRAMEWORK_PIPELINE_MANAGEMENT		= "FRAMEWORK_PIPELINE_MANAGEMENT";
}
